left_finger_position_controller:
  type: effort_controllers/JointPositionController
  joint: left_finger_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

right_finger_position_controller:
  type: effort_controllers/JointPositionController
  joint: right_finger_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

shoulder_controller:
  type: effort_controllers/JointPositionController
  joint: shoulder_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

elbow_controller:
  type: effort_controllers/JointPositionController
  joint: elbow_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
diff_drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: left_wheel_joint
  right_wheel: right_wheel_joint
  publish_rate: 50
  cmd_vel_timeout: 0.25
  wheel_separation: 0.4
  wheel_radius: 0.1
  enable_odom_tf: true
  base_frame_id: base_link
